version: "2"
services:
  laravel-php:
    container_name: laravel-php
    image: lavarel-php
    working_dir: /usr/share/nginx/html
    volumes:
      - /Users/matico/Workspace/Learning/laravel/:/usr/share/nginx/html
      - /Users/matico/Workspace/Learning/laravel/docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - laravel-local
  laravel-nginx:
    container_name: laravel-nginx
    image: nginx
    working_dir: /usr/share/nginx/html
    volumes:
      - /Users/matico/Workspace/Learning/laravel/:/usr/share/nginx/html
      - /Users/matico/Workspace/Learning/laravel/docker/laravel-local.conf:/etc/nginx/conf.d/default.conf
      - /Users/matico/Workspace/Learning/laravel/docker/log/:/var/log/nginx/
    volumes_from:
      - laravel-php
    ports:
      - "8080:80"
    networks: 
      - laravel-local
  laravel-db:
    container_name: laravel-db
    image: mysql:5.7
    volumes:
      - /Users/matico/Workspace/Learning/laravel/docker/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    networks:
      - laravel-local
  laravel-phpmyadmin:
    container_name: laravel-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "8082:80"
    external_links:
      - laravel-db:db
    networks:
      - laravel-local
networks: 
  laravel-local: